// File: data_sma_ibs_ah_putra_abhur_mataram.js
const DATA_SANTRI_SMA_IBS_AH_PUTRA_ABHUR_MATARAM = {
        "SMA IBS AH 10": ["ADLY ACHMAD FAIZ", "AHMAD KHOIRUL FATA", "ANINDRA RIFAT ANNAAFI", "ARSA RIZKY PADILLAH", "MOHAMAD RIZKY", "MUSA ABDULLAH", "NAUVAL DZAKA ADZ DZIKRA", "RIDWAN AL THAFUL AZMI", "RIZKY ANNADWA", "VITHO CAVALERA", "ZAIDIL ARQOM AL-FARUQ"]
    };